packages:
  # 所有应用包
  - "apps/*"
  # 所有基础工具包
  - "packages/*"
  # 所有组件包
  - "components/*"
  # 所有内部工具包
  - "internal/*"
  - "common/*"
catalog:
  "@vueuse/core": "^12.0.0"
  "@vueuse/rxjs": "^12.0.0"
  axios: "^1.7.8"
  crypto-js: "^4.2.0"
  defu: "^6.1.4"
  disable-devtool: "^0.3.8"
  jsrsasign: "^11.1.0"
  node-forge: "^1.3.1"
  pinia: "^2.3.0"
  rxjs: "^7.8.1"
  vant: "^4.9.15"
  vue: "^3.5.13"
