/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/dynamic-load-assets-image/': RouteRecordInfo<'/dynamic-load-assets-image/', '/dynamic-load-assets-image', Record<never, never>, Record<never, never>>,
    '/function-component/': RouteRecordInfo<'/function-component/', '/function-component', Record<never, never>, Record<never, never>>,
    '/graphQL/': RouteRecordInfo<'/graphQL/', '/graphQL', Record<never, never>, Record<never, never>>,
    '/markdown/': RouteRecordInfo<'/markdown/', '/markdown', Record<never, never>, Record<never, never>>,
    '/rxjs/': RouteRecordInfo<'/rxjs/', '/rxjs', Record<never, never>, Record<never, never>>,
    '/tan-stack-query/': RouteRecordInfo<'/tan-stack-query/', '/tan-stack-query', Record<never, never>, Record<never, never>>,
  }
}
